
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 27 23:34:49 COT 2016
//----------------------------------------------------

package compilador.etapa.pkg3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 31;
  public static final int ENTERO = 28;
  public static final int SI = 14;
  public static final int DISMINUIR = 7;
  public static final int RESTA = 3;
  public static final int NOIGUAL = 17;
  public static final int IDENTIFICADOR = 25;
  public static final int MENORIGUAL = 13;
  public static final int IGUAL = 11;
  public static final int SINO = 15;
  public static final int CARACTER = 27;
  public static final int AUMENTAR = 6;
  public static final int MIENTRAS = 19;
  public static final int BOOL = 30;
  public static final int SUMA = 2;
  public static final int MAIN = 21;
  public static final int APAREN = 37;
  public static final int MAYORIGUAL = 12;
  public static final int PYCOMA = 34;
  public static final int EOF = 0;
  public static final int ACORCH = 38;
  public static final int CPAREN = 36;
  public static final int KEYWORD = 26;
  public static final int CCORCH = 39;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOR = 10;
  public static final int ALLAVE = 32;
  public static final int VOID = 20;
  public static final int CLLAVE = 33;
  public static final int MAYOR = 9;
  public static final int T_DECIMAL = 23;
  public static final int NO = 16;
  public static final int ASIGNADOR = 8;
  public static final int T_BOLEANO = 24;
  public static final int PARA = 18;
  public static final int DIVISION = 5;
  public static final int FLOTANTE = 29;
  public static final int T_ENTERO = 22;
  public static final int MULTIPLICACION = 4;
}

