
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 26 17:20:36 COT 2016
//----------------------------------------------------

package compilador.etapa.pkg2;

import java.io.*;
import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Tue Jan 26 17:20:36 COT 2016
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\130\000\002\003\004\000\002\002\004\000\002\003" +
    "\003\000\002\004\011\000\002\005\003\000\002\005\002" +
    "\000\002\006\004\000\002\006\003\000\002\007\004\000" +
    "\002\007\004\000\002\007\004\000\002\007\003\000\002" +
    "\010\006\000\002\011\003\000\002\011\002\000\002\012" +
    "\005\000\002\012\003\000\002\013\003\000\002\013\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\015\004\000\002\015\005\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\017\004\000\002\017" +
    "\004\000\002\017\004\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\021\003\000\002\021\004\000" +
    "\002\022\005\000\002\022\005\000\002\022\005\000\002" +
    "\022\005\000\002\023\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\024\004\000\002\024\003" +
    "\000\002\025\004\000\002\025\004\000\002\026\004\000" +
    "\002\027\003\000\002\027\003\000\002\030\005\000\002" +
    "\031\003\000\002\031\003\000\002\031\003\000\002\032" +
    "\003\000\002\032\003\000\002\032\003\000\002\033\003" +
    "\000\002\033\004\000\002\033\005\000\002\034\011\000" +
    "\002\035\005\000\002\035\005\000\002\035\005\000\002" +
    "\035\005\000\002\036\003\000\002\036\003\000\002\036" +
    "\003\000\002\036\003\000\002\036\003\000\002\036\003" +
    "\000\002\037\006\000\002\040\004\000\002\040\003\000" +
    "\002\041\011\000\002\042\015\000\002\043\005\000\002" +
    "\044\011\000\002\045\004\000\002\045\003\000\002\046" +
    "\012\000\002\047\003\000\002\047\003\000\002\050\003" +
    "\000\002\050\002\000\002\051\005\000\002\051\003\000" +
    "\002\052\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\232\000\004\030\005\001\002\000\004\002\234\001" +
    "\002\000\004\027\226\001\002\000\014\002\uffff\026\016" +
    "\030\012\031\011\032\010\001\002\000\004\033\uffb0\001" +
    "\002\000\004\033\uffe7\001\002\000\004\033\uffe8\001\002" +
    "\000\004\033\uffe9\001\002\000\014\002\uffb2\026\uffb2\030" +
    "\uffb2\031\uffb2\032\uffb2\001\002\000\004\033\020\001\002" +
    "\000\014\002\001\026\016\030\012\031\011\032\010\001" +
    "\002\000\004\033\uffaf\001\002\000\014\002\uffb3\026\uffb3" +
    "\030\uffb3\031\uffb3\032\uffb3\001\002\000\004\047\021\001" +
    "\002\000\012\030\012\031\011\032\010\046\uffad\001\002" +
    "\000\004\033\225\001\002\000\006\044\223\046\uffae\001" +
    "\002\000\006\044\uffab\046\uffab\001\002\000\004\046\026" +
    "\001\002\000\004\042\027\001\002\000\022\020\041\024" +
    "\035\025\046\030\012\031\011\032\010\033\044\043\ufffc" +
    "\001\002\000\004\033\221\001\002\000\022\020\041\024" +
    "\035\025\046\030\012\031\011\032\010\033\044\043\ufffd" +
    "\001\002\000\022\020\ufff6\024\ufff6\025\ufff6\030\ufff6\031" +
    "\ufff6\032\ufff6\033\ufff6\043\ufff6\001\002\000\022\020\uffc9" +
    "\024\uffc9\025\uffc9\030\uffc9\031\uffc9\032\uffc9\033\uffc9\043" +
    "\uffc9\001\002\000\022\020\uffcb\024\uffcb\025\uffcb\030\uffcb" +
    "\031\uffcb\032\uffcb\033\uffcb\043\uffcb\001\002\000\004\047" +
    "\176\001\002\000\022\020\ufffa\024\ufffa\025\ufffa\030\ufffa" +
    "\031\ufffa\032\ufffa\033\ufffa\043\ufffa\001\002\000\004\044" +
    "\175\001\002\000\004\043\174\001\002\000\004\047\166" +
    "\001\002\000\004\044\165\001\002\000\026\020\uffc8\021" +
    "\147\022\151\024\uffc8\025\uffc8\030\uffc8\031\uffc8\032\uffc8" +
    "\033\uffc8\043\uffc8\001\002\000\006\012\100\047\101\001" +
    "\002\000\004\044\077\001\002\000\004\047\050\001\002" +
    "\000\022\020\uffca\024\uffca\025\uffca\030\uffca\031\uffca\032" +
    "\uffca\033\uffca\043\uffca\001\002\000\012\033\052\036\056" +
    "\037\055\040\054\001\002\000\016\013\070\014\067\015" +
    "\065\016\064\017\063\023\066\001\002\000\016\013\070" +
    "\014\067\015\065\016\064\017\063\023\066\001\002\000" +
    "\004\046\057\001\002\000\032\004\uffec\005\uffec\006\uffec" +
    "\007\uffec\013\uffec\014\uffec\015\uffec\016\uffec\017\uffec\023" +
    "\uffec\044\uffec\046\uffec\001\002\000\032\004\uffed\005\uffed" +
    "\006\uffed\007\uffed\013\uffed\014\uffed\015\uffed\016\uffed\017" +
    "\uffed\023\uffed\044\uffed\046\uffed\001\002\000\032\004\uffee" +
    "\005\uffee\006\uffee\007\uffee\013\uffee\014\uffee\015\uffee\016" +
    "\uffee\017\uffee\023\uffee\044\uffee\046\uffee\001\002\000\004" +
    "\042\060\001\002\000\022\020\041\024\035\025\046\030" +
    "\012\031\011\032\010\033\044\043\ufffc\001\002\000\004" +
    "\043\062\001\002\000\022\020\uffb4\024\uffb4\025\uffb4\030" +
    "\uffb4\031\uffb4\032\uffb4\033\uffb4\043\uffb4\001\002\000\012" +
    "\033\uffbc\036\uffbc\037\uffbc\040\uffbc\001\002\000\012\033" +
    "\uffbd\036\uffbd\037\uffbd\040\uffbd\001\002\000\012\033\uffbe" +
    "\036\uffbe\037\uffbe\040\uffbe\001\002\000\012\033\uffbb\036" +
    "\uffbb\037\uffbb\040\uffbb\001\002\000\012\033\uffbf\036\uffbf" +
    "\037\uffbf\040\uffbf\001\002\000\012\033\uffc0\036\uffc0\037" +
    "\uffc0\040\uffc0\001\002\000\012\033\073\036\056\037\055" +
    "\040\054\001\002\000\006\044\uffc2\046\uffc2\001\002\000" +
    "\006\044\uffc1\046\uffc1\001\002\000\012\033\076\036\056" +
    "\037\055\040\054\001\002\000\006\044\uffc4\046\uffc4\001" +
    "\002\000\006\044\uffc3\046\uffc3\001\002\000\022\020\ufff8" +
    "\024\ufff8\025\ufff8\030\ufff8\031\ufff8\032\ufff8\033\ufff8\043" +
    "\ufff8\001\002\000\012\033\121\036\056\037\055\040\054" +
    "\001\002\000\014\033\104\036\056\037\055\040\054\046" +
    "\ufff3\001\002\000\006\044\110\046\ufff4\001\002\000\006" +
    "\044\ufff1\046\ufff1\001\002\000\006\044\uffef\046\uffef\001" +
    "\002\000\006\044\ufff0\046\ufff0\001\002\000\004\046\107" +
    "\001\002\000\004\044\ufff5\001\002\000\012\033\104\036" +
    "\056\037\055\040\054\001\002\000\006\044\ufff2\046\ufff2" +
    "\001\002\000\004\044\uffe3\001\002\000\014\004\122\005" +
    "\131\006\124\007\127\044\uffce\001\002\000\014\004\122" +
    "\005\131\006\124\007\127\044\uffe0\001\002\000\004\044" +
    "\uffcd\001\002\000\004\044\uffe1\001\002\000\004\044\uffe2" +
    "\001\002\000\004\044\uffcf\001\002\000\022\004\122\005" +
    "\131\006\124\007\127\010\125\011\130\044\uffcc\047\101" +
    "\001\002\000\012\033\uffda\036\uffda\037\uffda\040\uffda\001" +
    "\002\000\006\044\uffd2\046\uffd2\001\002\000\012\033\uffd8" +
    "\036\uffd8\037\uffd8\040\uffd8\001\002\000\006\044\uffd1\046" +
    "\uffd1\001\002\000\012\033\132\036\056\037\055\040\054" +
    "\001\002\000\012\033\uffd7\036\uffd7\037\uffd7\040\uffd7\001" +
    "\002\000\006\044\uffd0\046\uffd0\001\002\000\012\033\uffd9" +
    "\036\uffd9\037\uffd9\040\uffd9\001\002\000\014\004\uffdb\005" +
    "\uffdb\006\uffdb\007\uffdb\044\uffdb\001\002\000\014\004\uffdc" +
    "\005\uffdc\006\uffdc\007\uffdc\044\uffdc\001\002\000\014\004" +
    "\uffd5\005\uffd5\006\uffd5\007\uffd5\044\uffd5\001\002\000\014" +
    "\004\122\005\131\006\124\007\127\044\uffdf\001\002\000" +
    "\012\033\140\036\056\037\055\040\054\001\002\000\014" +
    "\004\uffd4\005\uffd4\006\uffd4\007\uffd4\044\uffd4\001\002\000" +
    "\014\004\uffd3\005\uffd3\006\uffd3\007\uffd3\044\uffd3\001\002" +
    "\000\014\004\uffd6\005\uffd6\006\uffd6\007\uffd6\044\uffd6\001" +
    "\002\000\012\033\143\036\056\037\055\040\054\001\002" +
    "\000\014\004\uffdd\005\uffdd\006\uffdd\007\uffdd\044\uffdd\001" +
    "\002\000\014\004\uffde\005\uffde\006\uffde\007\uffde\044\uffde" +
    "\001\002\000\006\021\uffb8\022\uffb8\001\002\000\006\021" +
    "\147\022\151\001\002\000\004\047\155\001\002\000\022" +
    "\020\uffc7\024\uffc7\025\uffc7\030\uffc7\031\uffc7\032\uffc7\033" +
    "\uffc7\043\uffc7\001\002\000\004\042\152\001\002\000\022" +
    "\020\041\024\035\025\046\030\012\031\011\032\010\033" +
    "\044\043\ufffc\001\002\000\004\043\154\001\002\000\022" +
    "\020\uffba\024\uffba\025\uffba\030\uffba\031\uffba\032\uffba\033" +
    "\uffba\043\uffba\001\002\000\012\033\052\036\056\037\055" +
    "\040\054\001\002\000\004\046\157\001\002\000\004\042" +
    "\160\001\002\000\022\020\041\024\035\025\046\030\012" +
    "\031\011\032\010\033\044\043\ufffc\001\002\000\004\043" +
    "\162\001\002\000\006\021\uffb7\022\uffb7\001\002\000\006" +
    "\021\uffb9\022\uffb9\001\002\000\022\020\uffc6\024\uffc6\025" +
    "\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6\043\uffc6\001\002" +
    "\000\022\020\ufff9\024\ufff9\025\ufff9\030\ufff9\031\ufff9\032" +
    "\ufff9\033\ufff9\043\ufff9\001\002\000\012\033\052\036\056" +
    "\037\055\040\054\001\002\000\004\046\170\001\002\000" +
    "\004\042\171\001\002\000\022\020\041\024\035\025\046" +
    "\030\012\031\011\032\010\033\044\043\ufffc\001\002\000" +
    "\004\043\173\001\002\000\026\020\uffc5\021\uffc5\022\uffc5" +
    "\024\uffc5\025\uffc5\030\uffc5\031\uffc5\032\uffc5\033\uffc5\043" +
    "\uffc5\001\002\000\014\002\uffb1\026\uffb1\030\uffb1\031\uffb1" +
    "\032\uffb1\001\002\000\022\020\ufff7\024\ufff7\025\ufff7\030" +
    "\ufff7\031\ufff7\032\ufff7\033\ufff7\043\ufff7\001\002\000\010" +
    "\030\012\031\011\032\010\001\002\000\004\033\212\001" +
    "\002\000\004\044\201\001\002\000\012\033\052\036\056" +
    "\037\055\040\054\001\002\000\004\044\203\001\002\000" +
    "\004\033\205\001\002\000\004\046\206\001\002\000\006" +
    "\010\125\011\130\001\002\000\004\042\207\001\002\000" +
    "\022\020\041\024\035\025\046\030\012\031\011\032\010" +
    "\033\044\043\ufffc\001\002\000\004\043\211\001\002\000" +
    "\022\020\uffb6\024\uffb6\025\uffb6\030\uffb6\031\uffb6\032\uffb6" +
    "\033\uffb6\043\uffb6\001\002\000\004\012\213\001\002\000" +
    "\012\033\217\036\056\037\055\040\054\001\002\000\004" +
    "\044\uffb5\001\002\000\014\004\122\005\131\006\124\007" +
    "\127\044\uffe5\001\002\000\004\044\uffe6\001\002\000\022" +
    "\004\122\005\131\006\124\007\127\010\125\011\130\044" +
    "\uffe4\047\101\001\002\000\022\020\ufffb\024\ufffb\025\ufffb" +
    "\030\ufffb\031\ufffb\032\ufffb\033\ufffb\043\ufffb\001\002\000" +
    "\006\012\213\044\uffeb\001\002\000\004\044\uffea\001\002" +
    "\000\010\030\012\031\011\032\010\001\002\000\006\044" +
    "\uffac\046\uffac\001\002\000\006\044\uffaa\046\uffaa\001\002" +
    "\000\004\047\227\001\002\000\004\046\230\001\002\000" +
    "\004\042\231\001\002\000\022\020\041\024\035\025\046" +
    "\030\012\031\011\032\010\033\044\043\ufffc\001\002\000" +
    "\004\043\233\001\002\000\014\002\ufffe\026\ufffe\030\ufffe" +
    "\031\ufffe\032\ufffe\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\232\000\006\003\003\004\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\016\006\045\014\046\012" +
    "\047\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\016\006\046\016\047\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\016\021\050\024\051\022\052\023\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\032\005\037\006\030\007\035\010" +
    "\041\015\044\016\027\030\036\032\031\033\033\034\042" +
    "\042\046\044\032\001\001\000\002\001\001\000\026\007" +
    "\217\010\041\015\044\016\027\030\036\032\031\033\033" +
    "\034\042\042\046\044\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\037\147\040\145\041\144" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\050\035\052\001\001" +
    "\000\004\036\073\001\001\000\004\036\070\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\005\060\006\030\007" +
    "\035\010\041\015\044\016\027\030\036\032\031\033\033" +
    "\034\042\042\046\044\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\071\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\074\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\010\116\014\112" +
    "\020\114\021\111\022\113\026\115\031\117\001\001\000" +
    "\012\011\105\012\101\013\102\014\104\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\013\110" +
    "\014\104\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\023\141\001\001\000\010\023\135\024\134\025\133" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\023\125\027\122\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\132\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\023\135\025\140" +
    "\001\001\000\004\014\136\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\143\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\037\163\041\162\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\005\152\006\030\007" +
    "\035\010\041\015\044\016\027\030\036\032\031\033\033" +
    "\034\042\042\046\044\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\050\035\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\005\160\006\030\007" +
    "\035\010\041\015\044\016\027\030\036\032\031\033\033" +
    "\034\042\042\046\044\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\050\035\166\001\001\000\002\001" +
    "\001\000\002\001\001\000\032\005\171\006\030\007\035" +
    "\010\041\015\044\016\027\030\036\032\031\033\033\034" +
    "\042\042\046\044\032\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\016" +
    "\176\043\177\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\050\035\201\001\001\000\002\001\001\000" +
    "\004\026\203\001\001\000\002\001\001\000\004\027\122" +
    "\001\001\000\002\001\001\000\032\005\207\006\030\007" +
    "\035\010\041\015\044\016\027\030\036\032\031\033\033" +
    "\034\042\042\046\044\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\017\213\001\001\000\016\010\116" +
    "\014\214\020\215\021\111\022\113\026\115\001\001\000" +
    "\002\001\001\000\004\023\141\001\001\000\002\001\001" +
    "\000\006\023\125\027\122\001\001\000\002\001\001\000" +
    "\004\017\221\001\001\000\002\001\001\000\006\016\021" +
    "\052\223\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\032" +
    "\005\231\006\030\007\035\010\041\015\044\016\027\030" +
    "\036\032\031\033\033\034\042\042\046\044\032\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static void main(String args[]) throws Exception {
       // new parser(new Yylex(System.in)).parse();
        }

    public void syntax_error(Symbol s) {
        String resultado =  "Error de sintaxis... Linea: " + (s.right + 1) + " Columna: " + s.left + ". Texto: " + s.value;
        report_error(resultado, null);
        }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // parametro ::= tipodato IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(40/*parametro*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // parametros ::= parametro 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(39/*parametros*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // parametros ::= parametros PYCOMA parametro 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(39/*parametros*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // parametrosin ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(38/*parametrosin*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // parametrosin ::= parametros 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(38/*parametrosin*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // tiporetorno ::= VOID 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(37/*tiporetorno*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // tiporetorno ::= tipodato 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(37/*tiporetorno*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // funcion ::= tiporetorno IDENTIFICADOR APAREN parametrosin CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(36/*funcion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // funciones ::= funcion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(35/*funciones*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // funciones ::= funciones funcion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(35/*funciones*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // buclewhile ::= MIENTRAS APAREN condicion CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(34/*buclewhile*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // iniciafor ::= tipodato IDENTIFICADOR asignarvalor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(33/*iniciafor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // buclefor ::= PARA APAREN iniciafor PYCOMA condicion PYCOMA incredismivariable CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(32/*buclefor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // condicionsino ::= SINO APAREN condicion CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(31/*condicionsino*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // condicionessino ::= condicionsino 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(30/*condicionessino*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // condicionessino ::= condicionessino condicionsino 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(30/*condicionessino*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // condicionno ::= NO ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(29/*condicionno*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // condicional ::= NOIGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // condicional ::= MENORIGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // condicional ::= MAYORIGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // condicional ::= IGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // condicional ::= MENOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // condicional ::= MAYOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*condicional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // condicion ::= IDENTIFICADOR condicional IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*condicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // condicion ::= IDENTIFICADOR condicional valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*condicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // condicion ::= valor condicional IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*condicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // condicion ::= valor condicional valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*condicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // condicionsi ::= SI APAREN condicion CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(26/*condicionsi*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // condicionif ::= condicionsi condicionessino condicionno 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(25/*condicionif*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // condicionif ::= condicionsi condicionno 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(25/*condicionif*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // condicionif ::= condicionsi 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(25/*condicionif*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // buclecondicion ::= buclewhile 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(24/*buclecondicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // buclecondicion ::= buclefor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(24/*buclecondicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // buclecondicion ::= condicionif 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(24/*buclecondicion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // cambvalor ::= IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(23/*cambvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // cambvalor ::= operasignacion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(23/*cambvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // cambvalor ::= valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(23/*cambvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // cambiarvalor ::= IDENTIFICADOR ASIGNADOR cambvalor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(22/*cambiarvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // indis ::= DISMINUIR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*indis*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // indis ::= AUMENTAR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*indis*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // incredismivariable ::= IDENTIFICADOR indis 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*incredismivariable*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // oprcom ::= tipoopr IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(19/*oprcom*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // oprcom ::= tipoopr valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(19/*oprcom*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // oprcomplemento ::= oprcom 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*oprcomplemento*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // oprcomplemento ::= oprcomplemento oprcom 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*oprcomplemento*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tipoopr ::= DIVISION 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*tipoopr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // tipoopr ::= MULTIPLICACION 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*tipoopr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // tipoopr ::= RESTA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*tipoopr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tipoopr ::= SUMA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*tipoopr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // oprcomun ::= IDENTIFICADOR tipoopr IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*oprcomun*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // oprcomun ::= IDENTIFICADOR tipoopr valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*oprcomun*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // oprcomun ::= valor tipoopr IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*oprcomun*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // oprcomun ::= valor tipoopr valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*oprcomun*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // aritmetico ::= oprcomun oprcomplemento 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*aritmetico*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // aritmetico ::= oprcomun 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*aritmetico*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // operasignacion ::= incredismivariable 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*operasignacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // operasignacion ::= invocarmetodo 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*operasignacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // operasignacion ::= aritmetico 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*operasignacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // asignarvalor ::= ASIGNADOR IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*asignarvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // asignarvalor ::= ASIGNADOR valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*asignarvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // asignarvalor ::= ASIGNADOR operasignacion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*asignarvalor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipodato ::= T_BOLEANO 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*tipodato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipodato ::= T_DECIMAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*tipodato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipodato ::= T_ENTERO 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*tipodato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // crearvariable ::= tipodato IDENTIFICADOR asignarvalor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*crearvariable*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // crearvariable ::= tipodato IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*crearvariable*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // valor ::= BOOL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*valor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // valor ::= FLOTANTE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*valor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // valor ::= ENTERO 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*valor*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // penvio ::= IDENTIFICADOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*penvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // penvio ::= valor 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*penvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // parenvio ::= penvio 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*parenvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // parenvio ::= parenvio PYCOMA penvio 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*parenvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // parametrosenvio ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*parametrosenvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // parametrosenvio ::= parenvio 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*parametrosenvio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // invocarmetodo ::= IDENTIFICADOR APAREN parametrosenvio CPAREN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*invocarmetodo*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // linea ::= buclecondicion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*linea*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // linea ::= cambiarvalor PYCOMA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*linea*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // linea ::= crearvariable PYCOMA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*linea*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // linea ::= invocarmetodo PYCOMA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*linea*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lineacodigo ::= linea 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*lineacodigo*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lineacodigo ::= lineacodigo linea 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*lineacodigo*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lineascodigos ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*lineascodigos*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lineascodigos ::= lineacodigo 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*lineascodigos*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // principal ::= T_ENTERO MAIN APAREN CPAREN ALLAVE lineascodigos CLLAVE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*principal*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= principal 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*programa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= principal funciones 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*programa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

