package compilador.etapa.pkg2;

/**
 *
 * @author Cristian
 */
public enum Token {
    SUMA, RESTA, MULTIPLICACION, DIVISION, AUMENTAR, DISMINUIR, ASIGNADOR,MAYOR, MENOR, IGUAL, MAYORIGUAL, MENORIGUAL,
    SI, SINO, NO, PARA, MIENTRAS, VOID,MAIN, T_ENTERO, T_DECIMAL, T_BOLEANO,
    IDENTIFICADOR, KEYWORD, CARACTER, ENTERO, FLOTANTE, BOOL, CHAR,
    ALLAVE, CLLAVE, PYCOMA, COMA, CPAREN, APAREN, ACORCH, CCORCH
}
